export enum ADMIN_ROLES {
  ADMIN_NORMAL = 'ADMIN_NORMAL',
  ADMIN_SUPER = 'ADMIN_SUPER',
}
export const CONST_ADMIN_ROLES  = Object.values(ADMIN_ROLES);

export enum BRAND_CONSULT {
  CONSULT_COMPLETE = 'CONSULT_COMPLETE',
  CONSULT_CONTRACTED = 'CONSULT_CONTRACTED',
  CONSULT_DROPPED = 'CONSULT_DROPPED',
  CONSULT_IN_PROG = 'CONSULT_IN_PROG',
  NEW_CONSULT = 'NEW_CONSULT',
}
export const CONST_BRAND_CONSULT  = Object.values(BRAND_CONSULT);

export enum IP_STATUS {
  IP_ABUSE = 'IP_ABUSE',
}
export const CONST_IP_STATUS  = Object.values(IP_STATUS);

export enum ADMIN_STATUS {
  ONLINE = 'ONLINE',
  REJECTED = 'REJECTED',
  WAITING = 'WAITING',
}
export const CONST_ADMIN_STATUS  = Object.values(ADMIN_STATUS);

